---

service_name: "www_demo_f5nginx_vault_gcp"
service_name_vault: "www_demo_vault_gcp"
partition: "Tenant1"
as3_template_name: "as3_https_adv_template"
consul_private_ip: "{{ hostvars[groups['consul_systems'][0]].private_ip }}"

#######AS3 service definition (nginx)########
as3_template_file_name: "{{ as3_template_name + '.j2'}}"
as3_declaration_file_name: "{{ as3_template_name + '_' + service_name + '.json'}}"

as3_service_name: "vs_{{ service_name }}"
as3_virtual_address: "{{ vs_ip }}"
as3_pool_name: "pool_{{ service_name }}"
as3_service_label: "{{ service_name }}"
as3_waf_name: "waf_{{ service_name }}"

#######AS3 service definition (vault)#########
as3_pool_name_vault: "pool_{{ service_name_vault }}"