---
kind: pipeline
name: default

steps:

- name: Pull tfansible container
  image: tkam8/tfansible:latest
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
  commands:
  # Below pwd, ls commands are for debug purposes only
  - pwd
  - ls

- name: Deploy Terraform
  image: jmccann/drone-terraform:1
  plan: true
  root_dir: terraform-ansible-google/NGINX_F5_CDN/terraform/
  remote:
    backend: S3
    config:
      bucket: byocdn-drone-tf
      key: byocdn.tfstate
      region: ap-northeast-1

- name: Apply Ansible playbook
  image: plugins/ansible:1
  settings:
    playbook: terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/site.yml
    inventory: terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/inventory/hosts
    vault_password:
      from_secret: ansible_vault_password
    verbose: 2

trigger:
  branch:
  - master
  event:
  - push
  - pull_request