---
kind: pipeline
name: default

steps:

- name: Pull tfansible container and Deploy Terraform
  image: tkam8/tfansible:latest
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
    BIGIP_PASS:
      from_secret: bigip_pass
  commands:
  # Below pwd, ls commands are for debug purposes only
  - echo $${BIGIP_PASS}
  - pwd
  - ls
  - cd terraform-ansible-google/NGINX_F5_CDN/terraform/
  - terraform init -input=false
  - terraform apply -input=false -auto-approve
  #- terraform destroy -force

- name: SSH key preparation for Ansible Plugin
  image: tkam8/tfansible:latest
  environment:
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
  commands: 
  # write the ssh key to disk
  - mkdir /drone/src/gcp
  - printenv GCE_SSH_KEY > /drone/src/gcp/gcp_ssh_key
  - cat /drone/src/gcp/gcp_ssh_key
  - chmod 600 /drone/src/gcp/gcp_ssh_key

- name: Apply Ansible playbook
  image: tkam8/tfansible:latest
  commands: 
  - cd terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/
  - ansible-playbook --inventory inventory/hosts -vvvv site.yml

trigger:
  branch:
  - master
  event:
  - push
  - pull_request