---
kind: pipeline
name: default

steps:

- name: Pull tfansible container and Deploy Terraform
  image: tkam8/tfansible:latest
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
    ANSIBLE_VAULT_PASS:
      from secret: ansible_vault_password
  commands:
  # Below pwd, ls commands are for debug purposes only
  - env
  - echo "$$ANSIBLE_VAULT_PASS"
  - echo $$ANSIBLE_VAULT_PASS
  - pwd
  - ls
  - cd terraform-ansible-google/NGINX_F5_CDN/terraform/
  - terraform init -input=false
  - terraform apply -input=false -auto-approve
  #- terraform destroy -force

- name: SSH key preparation for Ansible Plugin
  image: tkam8/tfansible:latest
  commands: 
  # write the ssh key to disk
  - echo "$$ANSIBLE_VAULT_PASS"
  - echo $$ANSIBLE_VAULT_PASS
  - mkdir /drone/src/gcp
  - echo -n "$GCE_SSH_KEY" > /drone/src/gcp/gcp_ssh_key
  - echo -n "$ANSIBLE_VAULT_PASS" > /drone/src/gcp/ansible_vault_password
  - cat /drone/src/gcp/ansible_vault_password
  - chmod 600 /drone/src/gcp/gcp_ssh_key 
  - chmod 600 /drone/src/gcp/ansible_vault_password

- name: Apply Ansible playbook
  image: tkam8/tfansible:latest
  commands: 
  - ls -lah /drone/src/gcp/
  - echo "$$ANSIBLE_VAULT_PASS"
  - cd terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/
  - ansible-playbook --inventory inventory/hosts --vault-password-file /drone/src/gcp/ansible_vault_password -vvvv site.yml

trigger:
  branch:
  - master
  event:
  - push
  - pull_request