---
kind: pipeline
name: default

steps:

- name: Pull tfansible container and Deploy Terraform
  image: tkam8/tfansible:latest
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
    VAULT_PASS:
      from_secret: ans_vault
    SHORT_ENV:
      from_secret: this_is_a_veryvery_long_secret_name
    LONG_ENVIRONMENT_VARIABLE_NAME:
      from_secret: shortname
  commands:
  # Below pwd, ls commands are for debug purposes only
  - env
  - echo $${VAULT_PASS}
  - echo $${SHORT_ENV}
  - echo $${LONG_ENVIRONMENT_VARIABLE_NAME}
  - pwd
  - ls
  - cd terraform-ansible-google/NGINX_F5_CDN/terraform/
  - terraform init -input=false
  - terraform apply -input=false -auto-approve
  #- terraform destroy -force

- name: SSH key preparation for Ansible Plugin
  image: tkam8/tfansible:latest
  environment:
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
    VAULT_PASS:
      from_secret: ans_vault
  commands: 
  # write the ssh key to disk
  - echo $${VAULT_PASS}
  - echo ${VAULT_PASS}
  - echo "$${VAULT_PASS}"
  - echo "${VAULT_PASS}"
  - echo $$VAULT_PASS
  - echo $${GCE_SSH_KEY}
  - mkdir /drone/src/gcp
  - echo -n "$GCE_SSH_KEY" > /drone/src/gcp/gcp_ssh_key
  - echo -n "$VAULT_PASS" > /drone/src/gcp/ansible_vault_password
  - cat /drone/src/gcp/ansible_vault_password
  - chmod 600 /drone/src/gcp/gcp_ssh_key 
  - chmod 600 /drone/src/gcp/ansible_vault_password

- name: Apply Ansible playbook
  image: tkam8/tfansible:latest
  commands: 
  - ls -lah /drone/src/gcp/
  - echo $${VAULT_PASS}
  - cd terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/
  - ansible-playbook --inventory inventory/hosts --vault-password-file /drone/src/gcp/ansible_vault_password -vvvv site.yml


trigger:
  branch:
  - master
  event:
  - push
  - pull_request