---
kind: pipeline
name: default

steps:

- name: Pull tfansible container and Deploy Terraform
  image: tkam8/tfansible:latest
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
  commands:
  # Below pwd, ls commands are for debug purposes only
  - pwd
  - ls
  - cd terraform-ansible-google/NGINX_F5_CDN/terraform/
  - terraform init -input=false
  - terraform apply -input=false -auto-approve
  #- terraform destroy -force


- name: Apply Ansible playbook
  image: plugins/ansible:1
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: gcp_creds
    GCE_SSH_KEY:
      from_secret: gcp_ssh_key
  commands: 
  - env
  settings:
    playbook: terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/site.yml
    inventory: terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/inventory/hosts
    vault_password:
      from_secret: ansible_vault_password
    verbose: 2

trigger:
  branch:
  - master
  event:
  - push
  - pull_request