---
kind: pipeline
name: default

steps:

- name: Deploy Terraform Ansible Container with keys
  image: tkam8/tfansible:latest
  environment:
    GCP_CREDS:
      from_secret: gcp_creds
    GCP_SSH_KEY:
      from_secret: gcp_ssh_key
  commands:
  - pwd
  - ls
  #- cd /home/tfansible/NGINX-F5-CDN/terraform-ansible-google/NGINX_F5_CDN/terraform/
  - terraform init -input=false
  - terraform apply -input=false -auto-approve

- name: Apply Ansible playbook
  image: plugins/ansible:1
  settings:
    playbook: /home/tfansible/NGINX-F5-CDN/terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/site.yml
    inventory: /home/tfansible/NGINX-F5-CDN/terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/inventory/hosts
    vault_password:
      from_secret: ansible_vault_password
    verbose: 2

trigger:
  branch:
  - master
  event:
  - push
  - pull_request