---

# Configure nginx with proxy_pass and proxy_cache

- name: Setup nginx conf
  # Setting the upstream var used in the template to a var set in a previous play
  vars:
    upstreams: {{ hostvars['gke_systems']['ep_list'] }}
  template:
    src=nginx.conf.tpl
    dest=/etc/nginx/conf.d/upstream_test.conf
  notify: restart nginx



