
---

- name: Ubuntu initialization
  hosts: gcp_nginx_systems
  become: yes
  become_method: sudo
  become_user: root
  connection: ssh
  gather_facts: true
  roles: 
    - ubuntu_initialize

- name: Onboarding BIG-IP
  hosts: F5_systems
  gather_facts: false
  roles:
   - f5_onboarding

- name: BIG-IP AS3 declaration
  hosts: F5_systems
  gather_facts: false
  roles:
   - f5_as3_declare

- name: GKE nginxweb
  hosts: gke_systems
  connection: local
  gather_facts: true
  roles:
   - app1_gke_onboarding

- name: Player Dashboard
  hosts: player_dash_systems
  become: yes
  become_method: sudo
  become_user: root
  connection: ssh
  gather_facts: true
  roles:
   - player_dash_onboarding

- name: GCP NGINX Cache Config1
  hosts: gcp_nginx_systems
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: true
  roles:
   - nginx_configure