---
- name: Set BIG-IP admin password
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
      transport: cli
      user: admin
    commands: modify auth user admin password "{{ ADMIN_PASSWORD }}"
    validate_certs: no
  delegate_to: localhost
  register: setpasswd_status
  until: setpasswd_status is success
  delay: 5
  retries: 10

- name: enable iApps LX Package management in UI
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
      transport: cli
      user: admin
    commands: run /util bash -c "touch /var/config/rest/iapps/enable"
    validate_certs: no
  delegate_to: localhost

- name: Provision ASM at "nominal" level
  bigip_provision:
    module: asm
    level: nominal
    provider:
      server: "{{ inventory_hostname }}"
      server_port: "{{ ADMIN_HTTPS_PORT }}"
      user: "{{ ADMIN_USER }}"
      password: "{{ ADMIN_PASSWORD }}"
    validate_certs: no
  delegate_to: localhost