---
apiVersion: v1
kind: Deployment
metadata:
  namespace: upstream2
  labels:
    app: nginx-upstream2
  name: nginx-upstream2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-upstream2
  template:
    metadata:
      labels:
        app: nginx-upstream2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx-upstream2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-upstream2
  name: nginx-upstream2
  namespace: upstream2
spec:
  externalTrafficPolicy: Cluster
  ports:
    # Inside the cluster, what port does the service expose?
  - port: 80
    protocol: TCP
    # Which port do pods selected by this service expose?
    targetPort: 80
  selector:
    app: nginx-upstream2
  sessionAffinity: None
  # Make the service externally visible via the node IP
  type: NodePort