---

# Username and password will be grabbed from env var K8S_AUTH_USERNAME and K8S_AUTH_PASSWORD
- name: Create a k8s namespace
  k8s:
    name: upstream2
    api_version: v1
    host: "{{ gke_url }}"
    kubeconfig: "{{ kubeconfig }}"
    kind: Namespace
    state: present

- name: Create a NGINX pod and expose by reading the definition from a local file
  k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    src: "/home/tfansible/NGINX-F5-CDN/terraform-ansible-google/NGINX_F5_CDN/ansible/playbooks/roles/app1_gke_onboarding/templates/pod_nginx.yml"

- name: Get NGINX service
  k8s_facts:
    api_version: v1
    kind: Service
    name: nginx-upstream2
    namespace: upstream2
    kubeconfig: "{{ kubeconfig }}"
  register: nginx_svc

- name: Debug registered var containing service info
  debug: var=nginx_svc

